services:
  web:
    build: ./web
    ports:
      - '5173:5173'
    volumes:
      - ./web:/web
      - /web/node_modules
    environment:
      - NODE_ENV=development

  api:
    build:
      args:
        - target=dev
    volumes:
      - .:/api
    ports:
      - 8080:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      LANG: "C.UTF-8"

  nginx:
    container_name: "nginx"
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "api"
volumes:
  db:

