name: Update Swagger Docs

on:
  push:
    branches:
      - main

jobs:
  update-swagger-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger docs
      run: swag init -d ./cmd,./ -o ./docs

    - name: Commit Swagger docs
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add docs
        if ! git diff-index --quiet HEAD --; then
          git commit -m "github action: update swagger docs"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

